
### root
GET {{base}}/
Accept: application/json


### check_mem_all

GET {{base}}/check_mem_all/available?unit=G
Content-Type: application/json
Accept: application/json
Authorization: {{auth}}


### check_mem

GET {{base}}/check_mem/0?unit=G
Content-Type: application/json
Accept: application/json
Authorization: {{auth}}


### prepare_task

POST {{base}}/prepare_task
Content-Type: application/json
Accept: application/json
Authorization: {{auth}}

{
  "task": {
    "task_id": "6543",
    "instance_images": [
      "https://oss-prod.tishi.top/draw/sd/models/majicmixRealistic_v6-43331.jpg",
      "https://oss-prod.tishi.top/draw/sd/models/manmaruMix_v20-86277.jpg",
      "https://oss-prod.tishi.top/draw/sd/lora-models/33208-7934.jpg"
    ]
  }
}


### launch

POST {{base}}/launch
Content-Type: application/json
Accept: application/json
Authorization: {{auth}}

{
  "task": {
    "task_id": "6543",
    "instance_images": [
      "https://oss-prod.tishi.top/draw/sd/models/majicmixRealistic_v6-43331.jpg",
      "https://oss-prod.tishi.top/draw/sd/models/manmaruMix_v20-86277.jpg",
      "https://oss-prod.tishi.top/draw/sd/lora-models/33208-7934.jpg"
    ]
  },
  "launch": {
    "shell": false,
    "wrap_proxy": true,
    "proxy_command": "proxychains4 -q",
    "hf_hub_offline": true,
    "hf_accelerate": true,
    "skip_download_dataset_if_exists": true,
    "accelerate": {
      "mixed_precision": "fp16"
    }
  },
  "train": {
    "pretrained_model_name_or_path": "runwayml/stable-diffusion-v1-5",
    "instance_prompt": "a photo of sks dog",
    "max_train_steps": 40,
    "learning_rate": "2e-6",
    "with_prior_preservation": true,
    "class_prompt": "a photo of dog",
    "num_class_images": 20,
    "mixed_precision": "fp16",
    "prior_generation_precision": "fp16",
    "enable_xformers_memory_efficient_attention": true,
    "use_8bit_adam": true,
    "train_batch_size": 2,
    "gradient_accumulation_steps": 4
  }
}


### launch - mac

POST {{base}}/task/launch
Content-Type: application/json
Accept: application/json
Authorization: {{auth}}

{
  "task": {
    "task_id": "aaa",
    "instance_images": [
      "https://oss-prod.tishi.top/draw/sd/models/majicmixRealistic_v6-43331.jpg",
      "https://oss-prod.tishi.top/draw/sd/models/manmaruMix_v20-86277.jpg",
      "https://oss-prod.tishi.top/draw/sd/lora-models/33208-7934.jpg"
    ]
  },
  "launch": {
    "shell": false,
    "wrap_proxy": false,
    "hf_hub_offline": true,
    "hf_accelerate": true,
    "skip_download_dataset_if_exists": true,
    "accelerate": {
    }
  },
  "train": {
    "pretrained_model_name_or_path": "runwayml/stable-diffusion-v1-5",
    "instance_prompt": "a photo of sks dog",
    "max_train_steps": 40,
    "learning_rate": "2e-6",
    "with_prior_preservation": true,
    "class_prompt": "a photo of dog",
    "num_class_images": 20,
    "train_batch_size": 2,
    "gradient_accumulation_steps": 4
  }
}


### task - status

POST {{base}}/task/aaa/status
Content-Type: application/json
Accept: application/json
Authorization: {{auth}}

{
  "root_pid": "94171"
}


### task - generate_single

POST {{base}}/task/aaa/generate_single
Content-Type: application/json
Accept: application/json
Authorization: {{auth}}


### prepare_base_hf

POST {{base}}/prepare_base_hf
Content-Type: application/json
Accept: application/json
Authorization: {{auth}}

{
  "base_model_name": "GuoFeng3.4",
  "ext": "safetensors"
}


### task - list test_images

GET {{base}}/task/aaa/test_images
Content-Type: application/json
Accept: application/json
Authorization: {{auth}}


### task - get test_image

GET {{base}}/task/aaa/test_images/1-1d2082ea7f2349bc398a7ab83123708fa9e9274a.jpg/b64
Content-Type: application/json
Accept: application/json
Authorization: {{auth}}


### task - release model

POST {{base}}/task/aaa/release
Content-Type: application/json
Accept: application/json
Authorization: {{auth}}

{
  "base_model_name": "GuoFeng3.4"
}

